### ISSUE TITLE
Quickstart not so quick.

### ISSUE THREAD

**Issue by ckd002** [SkymindIO/dl4j-examples#4]
For future beginners I would like to suggest a few minor improvements to your Quickstart guide. 
1) The following instructions are provided: 

      git clone https://github.com/SkymindIO/dl4j-examples
      //or
      git clone https://github.com/SkymindIO/dl4j-0.0.3.3-examples`

 This makes it very much an option. The problem with this is that the example being used in the quickstart video is from the first link and never appears in the second.

2) After getting the code from github, the idea is to just hit run. Unfortunately this immediately breaks. I know this has been discussed in the google group and the solution of changing the version of NDJ4 to 0.0.3.5.1 has been posted there, but seems like something that should be fixed so that everyone who comes to the site doesn't have to fix it. 

3) The page goes on to say "Throughout the training, you should see some numeral-images pop up in small windows in the upper lefthand corner of your screen. Those are the reconstructions that prove your net actually works, and they look similar to these." The video also shows these images. However, .render(50) as shown in the code in the video does not appear in the downloaded code so the images never render for the user. While it's easily fixed, someone reading the instructions may see the blurb about changing the amount of images rendered but won't understand why there are no images at all.

**Comment by c0der1337** [comment]
good idea, because I had similar problems...

**Comment by chrisvnicholson** [comment]
fixed on the quickstart page. thanks for flagging.
